ARG WINE_BRANCH="stable"
FROM scottyhardy/docker-wine:${WINE_BRANCH}

ARG WINE_ARCH="win64"

ENV WINEDEBUG "fixme-all"

ENV RUN_AS_ROOT "yes"
ENV USE_XVFB "yes"
ENV XVFB_SERVER ":95"
ENV XVFB_SCREEN "0"
ENV XVFB_RESOLUTION "1024x768x8"
ENV DISPLAY ":95"
ENV WINEARCH $WINE_ARCH

#RUN export DISPLAY=:0 \
#    && (Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &) \
#    && wine wineboot --init \
#    && winetricks --unattended --force -q dotnet20 dotnet462 dotnet_verifier \
#    && while pgrep wineserver >/dev/null; do echo "Waiting for wineserver"; sleep 1; done \
#    && rm -rf $HOME/.cache/winetricks


RUN apt-get update && apt-get install xdelta3 curl unzip wget python3-doit libxml2 libxml2-dev --yes
RUN curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash - && \
    apt-get update && apt-get install nodejs --yes
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update \
    && rm -r aws*

RUN set -x -e; \
    entrypoint wineboot --init; \
    while true; do \
      if timeout 30m winetricks --unattended --force cmd dotnet8 corefonts; then \
        break; \
      fi \
    done; \
    while pgrep wineserver >/dev/null; do echo "Waiting for wineserver"; sleep 1; done; \
    rm -rf $HOME/.cache/winetricks;

